Adjust nullability for Agreement and Charge
vippsas/vipps-recurring-api pull request #191
Opened 2022-06-08 15:04 UTC by jhf

The changes adds nullability to the non required properties of
Agreement and Charge.
When using the Microsoft recommended OpenApi client, these changes
are required for a successful usage when running the latest
.Net 6 with the improved nullability handling.

2022-06-08 15:11 UTC, rognlien approved these changes

2022-06-08 15:31 UTC, rognlien requested changes
Hang on, need to take a closer look

2022-06-08 15:32 UTC, jhf commented
I was really surprised about the editing of this yaml file directly, I assumed you generated the file from  your source code, and that you would need to update some annotations there, and then regenerate this file.

2022-06-08 15:38 UTC, cloveras approved these changes
Thanks!

2022-06-08 15:39 UTC, cloveras requested changes
Waiting for @rognlien

2022-06-08 15:40 UTC, cloveras commented
> I was really surprised about the editing of this yaml file directly, I assumed you generated the file from your source code, and that you would need to update some annotations there, and then regenerate this file.

We have tried several approaches, end now use manually edited/tweaked/enriched specifications. We make frequent changes, and tight coupling to the build systems is not a plus.

2022-06-09 12:17 UTC, cloveras commented on docs/openapi.yaml
> +          nullable: true
Currency is required, so this is _one_ of the things the team is looking into.

2022-09-22 13:17 UTC, rognlien commented
Sorry for the veery late reply. We have been working on defining this properly. We will be making incremental changes to the OpenAPI file to reflect this.
Most the changes in this PR will be included or at least defined mor explicitly.

2022-09-22 13:17 UTC, closed without merging